[package]
name = "ftool"
version = "1.0.0"
description = "文件后缀处理工具"
authors = ["ftool"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "protocol-asset", "dialog-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.3"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1", features = ["rt-multi-thread"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
